USE [master]
GO

/****** Object:  Database [SmartParking]    Script Date: 7/7/2016 1:02:11 PM ******/
CREATE DATABASE [SmartParking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartParking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SmartParking.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SmartParking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SmartParking_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SmartParking] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartParking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmartParking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmartParking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmartParking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmartParking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmartParking] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmartParking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmartParking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmartParking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmartParking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmartParking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmartParking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmartParking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmartParking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmartParking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmartParking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmartParking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmartParking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmartParking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmartParking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmartParking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmartParking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmartParking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmartParking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SmartParking] SET  MULTI_USER 
GO

ALTER DATABASE [SmartParking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmartParking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmartParking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmartParking] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SmartParking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmartParking] SET  READ_WRITE 
GO


